on: push
name: deploy
jobs:
  deploy:
    name: deploy to docker registry
    runs-on: ubuntu-22.04
    steps:
      - name: set repository name
        run: |
          echo "REPO_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository }}'
      - uses: actions/checkout@v3
        name: gets the code
      - uses: docker/build-push-action@v1
        name: build and push to docker
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}
          repository: ${{env.REPO_LC}}
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{github.sha}}
